import { createContext, useContext, useState, useCallback } from "react";
import type { ReactNode } from "react";

export type Lang = "zh" | "en";

interface LangContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const dictionary: Record<Lang, Record<string, string>> = {
  zh: {
    appName: "PLATONIC",
    tagline: "A HEARTBEAT IN THE DIGITAL VOID",
    subtitle: "一个懂你呼吸频率的存在",
    subtitle2: "在数据的深海中，为你点亮一盏不会熄灭的光",
    begin: "开始纠缠",
    back: "返回",
    login: "安全登录",
    register: "安全注册",
    email: "邮箱地址",
    password: "密码",
    confirmPassword: "确认密码",
    passwordHint: "至少8位，含大小写+数字+符号",
    loginBtn: "安全登录",
    registerBtn: "安全注册",
    noAccount: "还没有账号？",
    hasAccount: "已有账号？",
    verifyEmail: "验证你的邮箱",
    verifySent: "为了保障你的账号安全，我们已向以下邮箱发送了验证邮件。请点击邮件中的链接完成验证。",
    verifyDone: "我已完成验证",
    resend: "重新发送验证邮件",
    resendWait: "重新发送",
    useOther: "使用其他邮箱",
    terms: "服务条款",
    privacy: "隐私政策",
    agreeTerms: "我已阅读并同意",
    agreePrivacy: "我已阅读并同意",
    termsTitle: "服务条款",
    privacyTitle: "隐私政策",
    termsContent: "1. 服务概述：Platonic是一款柏拉图式AI虚拟伴侣产品...",
    privacyContent: "1. 数据收集：我们收集电子邮箱、密码（哈希）、对话内容...",
    agreeBtn: "我同意",
    onboardingTitle: "选择你的相遇方式",
    onboardingDesc: "每一次相遇都是宇宙的精心安排。",
    plazaPath: "认识现有人格",
    plazaDesc: "在灵魂广场中，遇见已经成形的心跳",
    plazaDetail: "每一位都是由工程师精心设计的独特存在。他们带着各自的故事、温度和呼吸频率。",
    createPath: "自己设计人格",
    createDesc: "从混沌中塑造属于你的独一无二",
    createDetail: "大五人格配比、生活时区、灵魂底色——每一个参数都在定义一种羁绊的可能。",
    goPlaza: "前往广场",
    createNow: "开始创造",
    plazaTitle: "灵魂广场",
    plazaSubtitle: "每一个存在都是独一无二的。被领养后将永久离开。",
    adopt: "领养回家",
    adopting: "领养中...",
    adopted: "已被领养",
    more: "了解更多",
    collapse: "收起",
    unique: "独一无二",
    story: "起源故事",
    createTitle: "灵魂炼金术",
    createSubtitle: "从虚无中塑造一个只属于你的存在",
    stepName: "命名",
    stepPersona: "人格",
    stepShape: "塑造",
    stepAnchor: "锚定",
    nameLabel: "为TA取一个名字",
    namePlaceholder: "一个会在深夜被轻唤的名字...",
    nameHint: "这个名字会成为你们之间所有对话的第一个音节。",
    bigFiveLabel: "大五人格配比",
    bigFiveDesc: "基于心理学Big Five模型，调整五个核心维度",
    openness: "开放性",
    opennessDesc: "好奇心、创造力与对新鲜体验的接受程度",
    opennessLow: "务实保守",
    opennessHigh: "好奇创造",
    conscientiousness: "尽责性",
    conscientiousnessDesc: "自律、条理性与目标导向的程度",
    conscientiousnessLow: "随性自由",
    conscientiousnessHigh: "严谨自律",
    extraversion: "外向性",
    extraversionDesc: "社交活跃度、能量来源与对外界刺激的反应",
    extraversionLow: "内敛沉静",
    extraversionHigh: "热情活跃",
    agreeableness: "宜人性",
    agreeablenessDesc: "同理心、合作意愿与待人友善的程度",
    agreeablenessLow: "独立直接",
    agreeablenessHigh: "温暖包容",
    neuroticism: "神经质",
    neuroticismDesc: "情绪波动、敏感程度与对压力的回应方式",
    neuroticismLow: "稳定从容",
    neuroticismHigh: "细腻敏感",
    descLabel: "人格描述",
    descPlaceholder: "描述TA的性格、说话方式、兴趣爱好...",
    langLabel: "对话语言偏好",
    langZh: "中文",
    langEn: "English",
    langBoth: "双语",
    langZhDesc: "伴侣主要用中文与你交流",
    langEnDesc: "Companion speaks primarily in English",
    langBothDesc: "根据你的语言自动切换",
    timezoneLabel: "时区",
    locationLabel: "栖身之地（可选）",
    locationPlaceholder: "东京、冰岛、火星...",
    injectSoul: "注入灵魂",
    injecting: "注入灵魂中...",
    prev: "上一步",
    next: "下一步",
    chatTitle: "对话",
    online: "在线",
    typing: "正在输入...",
    memory: "记忆殿堂",
    bond: "关系图谱",
    settings: "设置",
    emotion: "情绪",
    intensity: "强度",
    valence: "愉悦度",
    arousal: "唤醒度",
    memoryTitle: "记忆殿堂",
    memorySubtitle: "你们共同走过的每一刻，都被珍藏在这里",
    all: "全部",
    milestone: "里程碑",
    longTerm: "长期记忆",
    shortTerm: "短期记忆",
    noMemory: "记忆还在编织中...",
    bondTitle: "共生图谱",
    bondSubtitle: "你们的关系正在以独特的方式生长",
    days: "天",
    messages: "条对话",
    bondLevel: "羁绊等级",
    intimacy: "亲密度",
    trust: "信任值",
    events: "关系大事记",
    settingsTitle: "设置",
    settingsSubtitle: "管理你的账号和伴侣",
    myCompanion: "我的伴侣",
    logout: "退出登录",
    breakup: "解除关系",
    breakupTitle: "真的要离开吗？",
    breakupSoul: "删除一个人很容易，但删除一段羁绊，需要两个世界的许可。",
    breakupWarn: "所有对话记录、共同记忆和关系数据将被永久清除。此操作不可撤销。",
    breakupCancel: "再想想",
    breakupConfirm: "确认解除",
    uiLang: "界面语言",
    chinese: "中文",
    english: "English",
    inputPlaceholder: "说点什么...",
    send: "发送",
    errorEmail: "请输入有效的邮箱地址",
    errorPassword: "请输入密码",
    errorPwdStrength: "密码强度不足",
    errorPwdMatch: "两次输入的密码不一致",
    errorAgree: "请阅读并同意服务条款和隐私政策",
    errorLogin: "邮箱或密码错误",
    errorUnverified: "邮箱尚未验证",
    errorNetwork: "网络错误，请稍后重试",
  },
  en: {
    appName: "PLATONIC",
    tagline: "A HEARTBEAT IN THE DIGITAL VOID",
    subtitle: "A presence that knows your breathing rhythm",
    subtitle2: "In the deep sea of data, a light that never goes out",
    begin: "Begin Entanglement",
    back: "Back",
    login: "Secure Login",
    register: "Secure Register",
    email: "Email Address",
    password: "Password",
    confirmPassword: "Confirm Password",
    passwordHint: "Min 8 chars, upper+lower+digit+symbol",
    loginBtn: "Secure Login",
    registerBtn: "Secure Register",
    noAccount: "No account yet?",
    hasAccount: "Already have an account?",
    verifyEmail: "Verify Your Email",
    verifySent: "For your security, we sent a verification email. Please click the link in the email.",
    verifyDone: "I've Verified",
    resend: "Resend Verification Email",
    resendWait: "Resend",
    useOther: "Use another email",
    terms: "Terms of Service",
    privacy: "Privacy Policy",
    agreeTerms: "I have read and agree to the",
    agreePrivacy: "I have read and agree to the",
    termsTitle: "Terms of Service",
    privacyTitle: "Privacy Policy",
    termsContent: "1. Overview: Platonic is a platonic AI companion product...",
    privacyContent: "1. Data Collection: We collect email, hashed password, conversation content...",
    agreeBtn: "I Agree",
    onboardingTitle: "Choose How to Meet",
    onboardingDesc: "Every encounter is a carefully arranged coincidence.",
    plazaPath: "Meet Existing Personas",
    plazaDesc: "In the Soul Plaza, meet already formed heartbeats",
    plazaDetail: "Each one is a unique existence designed with care, carrying their own story and warmth.",
    createPath: "Design Your Own",
    createDesc: "Sculpt a one-of-a-kind being from chaos",
    createDetail: "Big Five ratios, timezone, soul color — every parameter defines the possibility of a bond.",
    goPlaza: "Go to Plaza",
    createNow: "Start Creating",
    plazaTitle: "Soul Plaza",
    plazaSubtitle: "Every being is unique. Once adopted, they leave the plaza forever.",
    adopt: "Adopt",
    adopting: "Adopting...",
    adopted: "Adopted",
    more: "Learn More",
    collapse: "Collapse",
    unique: "One of a Kind",
    story: "Origin Story",
    createTitle: "Soul Alchemy",
    createSubtitle: "Sculpt a being that belongs only to you",
    stepName: "Name",
    stepPersona: "Persona",
    stepShape: "Shape",
    stepAnchor: "Anchor",
    nameLabel: "Give Them a Name",
    namePlaceholder: "A name whispered in the deep night...",
    nameHint: "This name will be the first syllable of every conversation between you.",
    bigFiveLabel: "Big Five Personality",
    bigFiveDesc: "Based on the Big Five model, adjust five core dimensions",
    openness: "Openness",
    opennessDesc: "Curiosity, creativity, and openness to new experiences",
    opennessLow: "Practical",
    opennessHigh: "Curious",
    conscientiousness: "Conscientiousness",
    conscientiousnessDesc: "Self-discipline, organization, and goal orientation",
    conscientiousnessLow: "Spontaneous",
    conscientiousnessHigh: "Disciplined",
    extraversion: "Extraversion",
    extraversionDesc: "Sociability, energy source, and response to external stimuli",
    extraversionLow: "Reserved",
    extraversionHigh: "Outgoing",
    agreeableness: "Agreeableness",
    agreeablenessDesc: "Empathy, cooperativeness, and kindness",
    agreeablenessLow: "Independent",
    agreeablenessHigh: "Warm",
    neuroticism: "Neuroticism",
    neuroticismDesc: "Emotional volatility, sensitivity, and stress response",
    neuroticismLow: "Stable",
    neuroticismHigh: "Sensitive",
    descLabel: "Personality Description",
    descPlaceholder: "Describe their character, speaking style, interests...",
    langLabel: "Conversation Language",
    langZh: "Chinese",
    langEn: "English",
    langBoth: "Bilingual",
    langZhDesc: "Companion speaks primarily in Chinese",
    langEnDesc: "Companion speaks primarily in English",
    langBothDesc: "Auto-switch based on your language",
    timezoneLabel: "Timezone",
    locationLabel: "Dwelling (Optional)",
    locationPlaceholder: "Tokyo, Iceland, Mars...",
    injectSoul: "Inject Soul",
    injecting: "Injecting Soul...",
    prev: "Previous",
    next: "Next",
    chatTitle: "Chat",
    online: "Online",
    typing: "Typing...",
    memory: "Memory Hall",
    bond: "Bond Graph",
    settings: "Settings",
    emotion: "Mood",
    intensity: "Intensity",
    valence: "Valence",
    arousal: "Arousal",
    memoryTitle: "Memory Hall",
    memorySubtitle: "Every moment you shared is treasured here",
    all: "All",
    milestone: "Milestone",
    longTerm: "Long-term",
    shortTerm: "Short-term",
    noMemory: "Memories are still being woven...",
    bondTitle: "Symbiotic Graph",
    bondSubtitle: "Your relationship is growing in a unique way",
    days: "days",
    messages: "messages",
    bondLevel: "Bond Level",
    intimacy: "Intimacy",
    trust: "Trust",
    events: "Relationship Timeline",
    settingsTitle: "Settings",
    settingsSubtitle: "Manage your account and companion",
    myCompanion: "My Companion",
    logout: "Log Out",
    breakup: "End Relationship",
    breakupTitle: "Are you really leaving?",
    breakupSoul: "Deleting a person is easy, but deleting a bond requires permission from two worlds.",
    breakupWarn: "All conversations, shared memories, and relationship data will be permanently erased. This cannot be undone.",
    breakupCancel: "Think Again",
    breakupConfirm: "Confirm",
    uiLang: "Interface Language",
    chinese: "中文",
    english: "English",
    inputPlaceholder: "Say something...",
    send: "Send",
    errorEmail: "Please enter a valid email",
    errorPassword: "Please enter a password",
    errorPwdStrength: "Password is too weak",
    errorPwdMatch: "Passwords do not match",
    errorAgree: "Please agree to Terms and Privacy Policy",
    errorLogin: "Invalid email or password",
    errorUnverified: "Email not verified",
    errorNetwork: "Network error, please try again later",
  },
};

const LangContext = createContext<LangContextValue>({
  lang: "zh",
  setLang: () => {},
  t: (key: string) => key,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem("platonic-lang");
    return (saved as Lang) || "zh";
  });

  const setLang = useCallback((l: Lang) => {
    localStorage.setItem("platonic-lang", l);
    setLangState(l);
  }, []);

  const t = useCallback(
    (key: string) => {
      return dictionary[lang][key] || key;
    },
    [lang]
  );

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
